version: "3.1"

services:

  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - "${APP_DATA}/plex:/config"
      - "${MEDIA_STORAGE}:/data"
    network_mode: host
    environment:
      - TZ=Europe/London
    restart: unless-stopped

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - "${APP_DATA}/syncthing:/config"
      - /mnt/data/backup:/data1
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

  beets:
    image: ghcr.io/linuxserver/beets
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${APP_DATA}/beets:/config"
      - "${MEDIA_STORAGE}/music:/music"
      - "${MEDIA_STORAGE}/downloads/music:/downloads"
    ports:
      - 8337:8337

  wiki:
    image: gollumwiki/gollum:master
    container_name: wiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${BACKUP_STORAGE}/jayr/notes/wiki:/wiki"
    ports:
      - 4567:4567
    restart: unless-stopped

  draw:
    image: jgraph/drawio
    container_name: drawio
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${BACKUP_STORAGE}/jayr/notes/wiki/diagrams:/data"
    ports:
      - 8080:8080
    restart: unless-stopped

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${APP_DATA}/nextcloud:/config"
      - "${BACKUP_STORAGE}/jayr/notes:/data"
    ports:
      - 443:443
    restart: unless-stopped
