version: "3.1"

services:

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3001:3000

  plex:
    image: plexinc/pms-docker
    volumes:
      - "${APP_DATA}/plex:/config"
      - "${MEDIA_STORAGE}:/data"
    network_mode: host
    environment:
      - TZ=Europe/London

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086 # http API port
      - 2003:2003 # Graphite port
    volumes:
      - "${APP_DATA}/influxdb:/var/lib/influxdb"
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_DB=app_metrics
