version: "3.1"

services:

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3001:3000

  plex:
    image: plexinc/pms-docker
    volumes:
      - "${APP_DATA}/plex:/config"
      - "${MEDIA_STORAGE}:/data"
    network_mode: host
    environment:
      - TZ=Europe/London

  airsonic:
    image: airsonic/airsonic
    ports:
      - 4040:4040
    volumes:
      - "${APP_DATA}/airsonic:/airsonic/data"
      - "${MEDIA_STORAGE}/music:/airsonic/music"
      - "${MEDIA_STORAGE}/playlists:/airsonic/playlists"

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086 # http API port
      - 2003:2003 # Graphite port
    volumes:
      - "${APP_DATA}/influxdb:/var/lib/influxdb"
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_DB=app_metrics

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - "${APP_DATA}/lidarr:/config"
      - "${MEDIA_STORAGE}/music:/music"
      # - /path/to/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  # collectd:
  #   image: quay.io/signalfuse/collectd
  #   network_mode: host
  #   privileged: true
  #   depends_on:
  #     - influxdb
  #   volumes:
  #     - "${APP_DATA}/collectd:/etc/collectd/managed_config"
  #   environment:
  #     - DISABLE_SFX_PLUGIN=True
  #     - SF_API_TOKEN=test
  #     - FQDN_LOOKUP=true
