version: "3.1"

networks:
  aar:
    external: true

services:

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - "${APP_DATA}/syncthing:/config"
      - /mnt/data/backup:/data1
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

  wiki:
    image: gollumwiki/gollum:master
    container_name: wiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${BACKUP_STORAGE}/jayr/notes/wiki:/wiki"
    command:
      - "--allow-uploads page"
    ports:
      - 4567:4567
    restart: unless-stopped

  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - "${APP_DATA}/flame:/app/data"
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    restart: unless-stopped

  # MEDIA

  mpd:
    image: philipwold/mpd
    ports:
      - "6600:6600"
      - "8000:8000"
    volumes:
      - "${MEDIA_STORAGE}/music:/var/lib/mpd/music"
      - "${MEDIA_STORAGE}/playlists:/var/lib/mpd/playlists"
    restart: unless-stopped

  beets:
    image: ghcr.io/linuxserver/beets
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${APP_DATA}/beets:/config"
      - "${MEDIA_STORAGE}/music:/music"
      - "${MEDIA_STORAGE}/downloads/music:/downloads"
    ports:
      - 8337:8337

  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - "${APP_DATA}/plex:/config"
      - "${MEDIA_STORAGE}:/data"
    network_mode: host
    environment:
      - TZ=Europe/London
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - "${APP_DATA}/tautulli:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 8181:8181

  #
  # AAAARR
  #

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${APP_DATA}/sabnzbd:/config"
      - "${MEDIA_STORAGE}/downloads/usenet:/downloads"
      - "${MEDIA_STORAGE}/downloads/usenet/incomplete:/incomplete-downloads"
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - aar

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${APP_DATA}/sonaar:/config"
      - "${MEDIA_STORAGE}/tv:/tv"
      - "${MEDIA_STORAGE}/downloads:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - aar

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${APP_DATA}/radaar:/config"
      - "${MEDIA_STORAGE}/films:/movies"
      - "${MEDIA_STORAGE}/downloads:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - aar

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/data:/config
      - "${APP_DATA}/prowlaar:/config"
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - aar
