version: "3.1"

services:

  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - "${APP_DATA}/plex:/config"
      - "${MEDIA_STORAGE}:/data"
    network_mode: host
    environment:
      - TZ=Europe/London
    restart: unless-stopped

  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
    volumes:
      - "${APP_DATA}/syncthing:/config"
      - /mnt/data/backup:/data1
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    restart: unless-stopped

  beets:
    image: ghcr.io/linuxserver/beets
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${APP_DATA}/beets:/config"
      - "${MEDIA_STORAGE}/music:/music"
      - "${MEDIA_STORAGE}/downloads/music:/downloads"
    ports:
      - 8337:8337

  airsonic:
    image: ghcr.io/linuxserver/airsonic
    container_name: airsonic
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - "${APP_DATA}/airsonic:/config"
      - "${MEDIA_STORAGE}/music:/music"
      - "${MEDIA_STORAGE}/playlists:/playlists"
      - "${MEDIA_STORAGE}/podcasts:/podcasts"
    ports:
      - 4040:4040
    restart: unless-stopped
